# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import service_rpc_pb2 as service__rpc__pb2


class CatalogStub(object):
    """Catalog Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.lookup = channel.unary_unary(
                '/Catalog/lookup',
                request_serializer=service__rpc__pb2.lookupRequestMessage.SerializeToString,
                response_deserializer=service__rpc__pb2.lookupResponseMessage.FromString,
                )
        self.buy_or_sell_stock = channel.unary_unary(
                '/Catalog/buy_or_sell_stock',
                request_serializer=service__rpc__pb2.orderRequestMessage.SerializeToString,
                response_deserializer=service__rpc__pb2.orderResponseMessage.FromString,
                )
        self.setLeader = channel.unary_unary(
                '/Catalog/setLeader',
                request_serializer=service__rpc__pb2.leaderMessage.SerializeToString,
                response_deserializer=service__rpc__pb2.leaderResponse.FromString,
                )


class CatalogServicer(object):
    """Catalog Service Definition
    """

    def lookup(self, request, context):
        """lookup method for communication between front end server or order service and catalog service 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def buy_or_sell_stock(self, request, context):
        """buy method (order service to catalog service)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.lookup,
                    request_deserializer=service__rpc__pb2.lookupRequestMessage.FromString,
                    response_serializer=service__rpc__pb2.lookupResponseMessage.SerializeToString,
            ),
            'buy_or_sell_stock': grpc.unary_unary_rpc_method_handler(
                    servicer.buy_or_sell_stock,
                    request_deserializer=service__rpc__pb2.orderRequestMessage.FromString,
                    response_serializer=service__rpc__pb2.orderResponseMessage.SerializeToString,
            ),
            'setLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.setLeader,
                    request_deserializer=service__rpc__pb2.leaderMessage.FromString,
                    response_serializer=service__rpc__pb2.leaderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Catalog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Catalog(object):
    """Catalog Service Definition
    """

    @staticmethod
    def lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Catalog/lookup',
            service__rpc__pb2.lookupRequestMessage.SerializeToString,
            service__rpc__pb2.lookupResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def buy_or_sell_stock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Catalog/buy_or_sell_stock',
            service__rpc__pb2.orderRequestMessage.SerializeToString,
            service__rpc__pb2.orderResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def setLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Catalog/setLeader',
            service__rpc__pb2.leaderMessage.SerializeToString,
            service__rpc__pb2.leaderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class OrderStub(object):
    """Order Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.trade = channel.unary_unary(
                '/Order/trade',
                request_serializer=service__rpc__pb2.tradeRequestMessage.SerializeToString,
                response_deserializer=service__rpc__pb2.tradeResponseMessage.FromString,
                )
        self.healthCheck = channel.unary_unary(
                '/Order/healthCheck',
                request_serializer=service__rpc__pb2.checkMessage.SerializeToString,
                response_deserializer=service__rpc__pb2.checkResponse.FromString,
                )
        self.setLeader = channel.unary_unary(
                '/Order/setLeader',
                request_serializer=service__rpc__pb2.leaderOrderMessage.SerializeToString,
                response_deserializer=service__rpc__pb2.leaderResponse.FromString,
                )
        self.lookupOrder = channel.unary_unary(
                '/Order/lookupOrder',
                request_serializer=service__rpc__pb2.lookupOrderRequestMessage.SerializeToString,
                response_deserializer=service__rpc__pb2.lookupOrderResponseMessage.FromString,
                )
        self.update_db = channel.unary_unary(
                '/Order/update_db',
                request_serializer=service__rpc__pb2.syncRequestMessage.SerializeToString,
                response_deserializer=service__rpc__pb2.syncResponseMessage.FromString,
                )
        self.synchronize_database = channel.unary_unary(
                '/Order/synchronize_database',
                request_serializer=service__rpc__pb2.recoveryRequestMessage.SerializeToString,
                response_deserializer=service__rpc__pb2.recoveryResponseMessage.FromString,
                )
        self.send_db_data = channel.unary_unary(
                '/Order/send_db_data',
                request_serializer=service__rpc__pb2.dataRequestMessage.SerializeToString,
                response_deserializer=service__rpc__pb2.dataResponseMessage.FromString,
                )


class OrderServicer(object):
    """Order Service Definition
    """

    def trade(self, request, context):
        """trade method for communication between front-end server and order service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def healthCheck(self, request, context):
        """method to check health of order service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setLeader(self, request, context):
        """metod to set leader of order services
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def lookupOrder(self, request, context):
        """order lookup method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_db(self, request, context):
        """mehthod to update followers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def synchronize_database(self, request, context):
        """method to update database after recovering from crash
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def send_db_data(self, request, context):
        """method to send database records to service after it recovers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'trade': grpc.unary_unary_rpc_method_handler(
                    servicer.trade,
                    request_deserializer=service__rpc__pb2.tradeRequestMessage.FromString,
                    response_serializer=service__rpc__pb2.tradeResponseMessage.SerializeToString,
            ),
            'healthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.healthCheck,
                    request_deserializer=service__rpc__pb2.checkMessage.FromString,
                    response_serializer=service__rpc__pb2.checkResponse.SerializeToString,
            ),
            'setLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.setLeader,
                    request_deserializer=service__rpc__pb2.leaderOrderMessage.FromString,
                    response_serializer=service__rpc__pb2.leaderResponse.SerializeToString,
            ),
            'lookupOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.lookupOrder,
                    request_deserializer=service__rpc__pb2.lookupOrderRequestMessage.FromString,
                    response_serializer=service__rpc__pb2.lookupOrderResponseMessage.SerializeToString,
            ),
            'update_db': grpc.unary_unary_rpc_method_handler(
                    servicer.update_db,
                    request_deserializer=service__rpc__pb2.syncRequestMessage.FromString,
                    response_serializer=service__rpc__pb2.syncResponseMessage.SerializeToString,
            ),
            'synchronize_database': grpc.unary_unary_rpc_method_handler(
                    servicer.synchronize_database,
                    request_deserializer=service__rpc__pb2.recoveryRequestMessage.FromString,
                    response_serializer=service__rpc__pb2.recoveryResponseMessage.SerializeToString,
            ),
            'send_db_data': grpc.unary_unary_rpc_method_handler(
                    servicer.send_db_data,
                    request_deserializer=service__rpc__pb2.dataRequestMessage.FromString,
                    response_serializer=service__rpc__pb2.dataResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Order', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Order(object):
    """Order Service Definition
    """

    @staticmethod
    def trade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Order/trade',
            service__rpc__pb2.tradeRequestMessage.SerializeToString,
            service__rpc__pb2.tradeResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def healthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Order/healthCheck',
            service__rpc__pb2.checkMessage.SerializeToString,
            service__rpc__pb2.checkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def setLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Order/setLeader',
            service__rpc__pb2.leaderOrderMessage.SerializeToString,
            service__rpc__pb2.leaderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def lookupOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Order/lookupOrder',
            service__rpc__pb2.lookupOrderRequestMessage.SerializeToString,
            service__rpc__pb2.lookupOrderResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update_db(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Order/update_db',
            service__rpc__pb2.syncRequestMessage.SerializeToString,
            service__rpc__pb2.syncResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def synchronize_database(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Order/synchronize_database',
            service__rpc__pb2.recoveryRequestMessage.SerializeToString,
            service__rpc__pb2.recoveryResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def send_db_data(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Order/send_db_data',
            service__rpc__pb2.dataRequestMessage.SerializeToString,
            service__rpc__pb2.dataResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
